dist: xenial

services:
  - postgresql
  - xvfb
addons:
  postgresql: "9.4"
  chrome: stable
before_script:
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
  - cp decide/local_settings.travis.py decide/local_settings.py
  - "export DISPLAY=:99.0"
  - sleep 3    
language: python
python:
  - "3.6"
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
  - pip install codacy-coverage
  - pip install selenium
  - sudo apt-get install chromium-browser
  - sudo apt-get install -y firefox
  - wget -N https://chromedriver.storage.googleapis.com/87.0.4280.88/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip 
  - rm chromedriver_linux64.zip
  - sudo mv -f chromedriver /usr/bin
  - sudo chmod +x /usr/bin/chromedriver  
script:
  - cd decide
  - cp local_settings.travis.py local_settings.py
  - coverage run --branch --source=. ./manage.py test mixnet --keepdb
  - coverage xml
  - python-codacy-coverage -r coverage.xml
deploy:
  provider: heroku
  app: examen-egc-probando
  strategy: git
  apikey: $HEROKU_AUTH_TOKEN
notifications:
  email:
    recipients:
      - jorandmol@alum.us.es
    on_success: always
    on_failure: always
