dist: xenial

services:
  - postgresql
  - xvfb
addons:
  postgresql: "9.4"
  chrome: stable
before_script:
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
  - "export DISPLAY=:99.0"
  - sleep 3    
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codacy-coverage
  - pip install selenium
  - sudo apt-get install chromium-browser
  - wget -N https://chromedriver.storage.googleapis.com/87.0.4280.88/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip 
  - rm chromedriver_linux64.zip
  - sudo mv -f chromedriver /usr/bin
  - sudo chmod +x /usr/bin/chromedriver  
script:
  - cd decide
  - cp local_settings.travis.py local_settings.py
  - coverage run --branch --source=. ./manage.py test mixnet --keepdb
  - coverage xml
  - python-codacy-coverage -r coverage.xml
deploy:
  provider: heroku
  app: examen-egc-probando
  strategy: git
  apikey: 
    secure: BW8/nwVUpkQYJGkcWuQTEbXWysqyEsxudWk9lWVc9CWcP1SFx27ena1w1lqSJuxkkrrP5Q2B7/sNyEaFKnOhck0L5YfrlTIb4uyRLgWs8KjszfTvLfXAoeAYBRsRPYrhOTfD/OWT38UaCbGO4L4OLChcAyTAfLAuv4fQMkZ5TVtZnADTQ1MjYoEBES9FAknnENDbpfDeE4Dgupz/BKFjkHX0D3ppljQu9kKw8SV0r4L/YqnEDJkp+zqx+Hz8QGNeFnJVSEn6O0tQPeIccvqlutDg/YgG8c4aEu88wm8IHYqaIMx2mr2Wi3vvcNBj5uUmM5Bk8VzOeBoHD8BLUbuJiYiHvkXQCTwhe2boQQuet08zv9dr6goDRyN9W/NJSQ3kFbQRO9oszjEsByosWzhaBimuM8b78pmOQISMzN8aEdVUVaL7C72MwVldC2vC6C+HFJdPj4UXk+G5N+go87jhJTKaeiR/HXdb20SYo+ZaxwNBjaTBuzFjQ+HsNmCecFhrJ7l0wD/cipP7ekXOSL/m+BFp6Wfub42vazl8KxZj27OVdbmzufFgpwlB78fprxAZHd/wAHntiFsrj98FWN6VnFa8UHKlb4jpnwvklfWTdzB4IK/QB8Xxn30TXoSzttb2fKXEMv5eyqNE8tDvFpUxGaKWOwDeA+B+4M7FDsb1nW0=
notifications:
  email:
    recipients:
      - jorandmol@alum.us.es
    on_success: always
    on_failure: always